version: "3"

services:
  node:
    container_name: node
    build:
      context: .
      dockerfile: "Dockerfile"
    volumes:
      - .:/node
    tty: true
    ports:
      # react
      - 3000:3000
      # firebase emulator
      - 9005:9005
      - 9099:9099
      - 8080:8080
      - 9000:9000
      - 5000:5000
      - 9199:9199
      - 4000:4000
