version: "3"

services:
  node:
    container_name: node
    build:
      context: .
      dockerfile: "Dockerfile"
    volumes:
      - .:/home
    working_dir: /home
    tty: true
    ports:
      - 3000:3000
