name: VPS Deploy CI
on:
  push:
    branches: [main]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
 
#       - name: VPS Deploy
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.HOST }}
#           username: ${{ secrets.USERNAME }}
#           key: ${{ secrets.KEY }}
#           port: ${{ secrets.PORT }}
#           script: |
#             cd kids-pj/
#             eval `ssh-agent`
#             ssh-add ~/.ssh/git_pull
#             git pull origin main
#             docker-compose restart node
